### PR TITLE
My vision of number input

### PR DESCRIPTION
**Pull request by abenkovskii**
1. Works for negative numbers
2. Has default value
3. Probably has better user interface

### CODE REVIEW

**Comment by abenkovskii** [comment]
see changes in
lib_menu.ks
lib_number_dialog.ks
and
example_lib_number_dialog.ks

All other changes are pulled from the main repository.

**Comment by abenkovskii** [comment]
@akrasuski1 What do you think about this?

**Comment by akrasuski1** [comment]
The idea is very nice - the increments particularly. But the graphics (yeah, I know) don't really look nice to me. I'll take care of it, and then it's ready, OK?

**Comment by abenkovskii** [comment]
@akrasuski1 OK.
By the way: if you care about graphics you may implement lib_gui_box.ks with two functions:
1. draw_gui_box(x1, y1, x2, y2).
2. and draw_wide_gui_box(line_umber_1, line_umber_2) that calls draw_gui_box(1, line_number_1, terminal:width, line_number_2).
This way all gui libraries will have an easy way to make their graphics pretty. It will also reduce the amount of repeated code and therefore make fancy graphics more space-efficient.

**Comment by akrasuski1** [comment]
Actually, that is exactly the thing I am working on. 
It may be a bit of a stretch goal, but I also intend to be able to display two or three windows at once - it seems simple, but if I want them to update in parallel, there would have to be some kind of simple OS switching processes. Due to the amount of work to be done, for now I just copy and paste that simple code.

**Comment by abenkovskii** [comment]
@akrasuski1 If you are doing a fully featured gui library don't forget to react on terminal resize event.
P.S. If it's a stretch goal may I make a stopgap that will eventually be replaced by your library?

**Comment by akrasuski1** [comment]
Hmm, I don't know yet what the best interface would be - considering the single-procesor existence of kOS, the window code would be very closely connected with process code. I think the only way to implement multiple processes right now is to make people do their stuff as two functions - for example, menu would be: "open_window_menu" and "update_window_menu", with the second one taking process_state as parameter. I do have a simple prototype working right now, but it needs some polish. Right now the "OS", or window management code hardcodes all processes and exits as soon as one of the processes exit.
So, to answer your question: don't make a temporary placeholder, because it's very likely that any programs created basing on it will have to be updated after my gui library anyway. And it's not only about changing one or two lines, but splitting into two different functions, which is quite a major design change.

**Comment by abenkovskii** [comment]
> hardcodes all processes

May be lib_exec with it's power to make global locks from strings will help

**Comment by akrasuski1** [comment]
Yes, that's what I eventually intend to do.

**Pull request merged**
